# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
#    - typecheck
    - unconvert
    - unused
