on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
name: Update README check
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: generate README.md
        run: make README.md

      - name: check for uncommitted changes
        run: git diff --exit-code