on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
name: Tests with spanner emulator
jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      spanner:
        env:
          SPANNER_INSTANCE_ID: ${{env.SPANNER_INSTANCE_ID}}
          SPANNER_PROJECT_ID: ${{env.SPANNER_PROJECT_ID}}
        image: roryq/spanner-emulator:1.4.0
    env:
      SPANNER_INSTANCE_ID: inst
      SPANNER_PROJECT_ID: proj
      SPANNER_EMULATOR_HOST: spanner:9010
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...